spring.application.name=notification-service
server.port=8083
management.endpoints.web.exposure.include=health,info
notifications.dry-run=true
notifications.max-attempts=3
notifications.email-url=http://localhost:9083/providers/email
notifications.sms-url=http://localhost:9083/providers/sms
notifications.push-url=http://localhost:9083/providers/push
