spring.application.name=meeting-room-scheduler-api
server.port=8087
management.endpoints.web.exposure.include=health,info
spring.datasource.url=jdbc:h2:mem:meeting_room_scheduler_api;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
